Bug fix
temporalio-server(main) uv run example.py
Installed 5 packages in 12ms
Could not find or access bundled temporal binary 'temporal'. Build process may have failed. Details: Binary path resolved by as_file is not a file: /Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/
python3.13/site-packages/temporalio_server/bin/temporal
Traceback (most recent call last):
  File "/Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/__init__.py", line 24, in get_binary_path
    raise FileNotFoundError(
        f"Binary path resolved by as_file is not a file: {binary_path}"
    )
FileNotFoundError: Binary path resolved by as_file is not a file: /Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/bin/temporal
Traceback (most recent call last):
  File "/Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/__init__.py", line 24, in get_binary_path
    raise FileNotFoundError(
        f"Binary path resolved by as_file is not a file: {binary_path}"
    )
FileNotFoundError: Binary path resolved by as_file is not a file: /Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/bin/temporal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dan/src/temporalio/temporalio-server/example.py", line 58, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/Users/dan/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Users/dan/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/dan/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/dan/src/temporalio/temporalio-server/example.py", line 39, in main
    async with DevServer() as server:
               ~~~~~~~~~^^
  File "/Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/__init__.py", line 84, in __aenter__
    binary_path = get_binary_path()
  File "/Users/dan/.cache/uv/environments-v2/example-ea3c32c71a433f14/lib/python3.13/site-packages/temporalio_server/__init__.py", line 34, in get_binary_path
    raise FileNotFoundError("Temporal CLI binary not found.") from e
FileNotFoundError: Temporal CLI binary not found.